# Generated by Django 5.2.7 on 2025-10-19 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Subscription',
            new_name='ConfirmedEmail',
        ),
        migrations.RenameField(
            model_name='confirmedemail',
            old_name='date_subscribed',
            new_name='confirmed_at',
        ),
    ]
