# Generated by Django 5.2.7 on 2025-11-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawquestion',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawquestion',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
